

name: JPackage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maven_version:
    uses: sfuhrm/github_workflows/.github/workflows/maven-expression.yml@main
    with:
      java_version: 21
      expression: project.version
  jpackage:
    needs: maven_version
    uses: sfuhrm/github_workflows/.github/workflows/jpackage.yml@main
    env:
      VERSION: ${{ needs.maven_version.outputs.expression_value }}
    with:
      java_version: 21
      artifact_name: jpackage
      jpackage_input: target/Uhr-$VERSION-app/Uhr-$VERSION
      jpackage_name: uhr
      jpackage_jarfile: target/Uhr-$VERSION-app/Uhr-$VERSION/lib/Uhr-$VERSION.jar
      jpackage_license: target/Uhr-$VERSION-app/Uhr-$VERSION/LICENSE
      jpackage_vendor: Stephan Fuhrmann
      jpackage_copyright: Stephan Fuhrmann
      jpackage_description: Analog clock
      jpackage_mainclass: de.sfuhrm.uhr.Uhr
      jpackage_linux_deb_maintainer: s@sfuhrm.de
      jpackage_linux_app_category: misc
      jpackage_win_upgrade_uuid: 47f95ddc-1ed8-11f0-88dc-3fbe170393f3
